; =============================================================
;  Ansible EC2 Inventory
;  Control Node  : 13.201.81.29
;  Web Servers   : web1 | web2 | web3
; =============================================================

[web]
35.154.188.207 ansible_host=35.154.188.207 host_alias=web1
13.232.12.246      ansible_host=13.232.12.246      host_alias=web2
13.235.75.28  ansible_host=13.235.75.28  host_alias=web3

[web:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=ansible_ec2.pem
